services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - intellecta-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:80"
    volumes:
      - ./backend/files:/var/www/files.intellecta
      - ./backend/api:/var/www/api.intellecta
    networks:
      intellecta-network:
        aliases:
          - api.intellecta
          - files.intellecta
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_container
    ports:
      - "8081:8080"
    volumes:
      - ./backend/api/public/swagger.json:/tmp/swagger.json:ro
    environment:
      SWAGGER_JSON: /tmp/swagger.json
    networks:
      - intellecta-network
  database:
    image: mysql:9.3.0
    container_name: database_container
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      MYSQL_ROOT_PASSWORD: SegredoInsano
      MYSQL_DATABASE: intellecta
      MYSQL_USER: www_root
      MYSQL_PASSWORD: foraelecriadoParahabitaruminstantequefosseNasvizinhascasdoteucoracao
    ports:
      - "3306:3306"
    networks:
      - intellecta-network
networks:
  intellecta-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.255.0/24
