services:
  # frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    # container_name: frontend_container
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    # networks:
    #   - intellecta-public-network
      # depends_on:
      # - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:80"
    volumes:
      - ./backend/files:/var/www/files.intellecta
      - ./backend/api:/var/www/api.intellecta
    env_file:
      - ./database/.env
      - ./backend/.env
    depends_on:
      - redis
      - database
    networks:
      intellecta-private-network: {}
      intellecta-public-network:
          aliases:
            - api.intellecta
            - files.intellecta
  email-worker:
    build:
      context: ./email_worker
      dockerfile: Dockerfile
    container_name: email_worker_container
    env_file:
      - ./email_worker/.env
    depends_on:
      - redis
    networks:
      - intellecta-public-network
      - intellecta-private-network

  redis:
    image: redis:8.2.1
    container_name: redis_container
    networks:
      - intellecta-private-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_container
    ports:
      - "8081:8080"
    volumes:
      - ./backend/api/public/swagger.json:/tmp/swagger.json:ro
    environment:
      SWAGGER_JSON: /tmp/swagger.json
    networks:
      - intellecta-public-network

  database:
    image: mysql:9.3.0
    container_name: database_container
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    env_file:
      - ./database/.env
    networks:
      - intellecta-private-network

networks:
  intellecta-public-network:
    driver: bridge
  intellecta-private-network:
    driver: bridge
    internal: true
